controller_list:
  - name: arm_controller
    type: follow_joint_trajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint_arm_rotary
initial:  # Define initial robot poses per group
  - group: cobot_arm
    pose: zero