import matplotlib.pyplot as plt

def Nav_route_visual(static_map, path):
    """
    Visualization of routes generated by navigation algorithms

    Args:
        static_map (np.array): occupancy map on 2D grid map
        path (list): The set of points on the route calculated by the navigation algorithm.
    """
    
    # 'gray_r' means reversed grayscale
    plt.imshow(static_map, cmap="gray_r", origin="lower") 
    
    # Extract the x and y coordinates of the path
    x_coords = [point[1] for point in path]
    y_coords = [point[0] for point in path]

    # Plot the path on top of the static_map
    plt.plot(x_coords, y_coords, color="r", linewidth=2)
    plt.show()