# PbClient
Client:
  enable_GUI: True            # If True, the GUI will be enabled.
  enable_Debug: False         # If False, the debug visualizer will be disabled.
  enable_capture: True
  Gravity: [0, 0, -9.8]
  numSolverIterations: 1000   # Set the number of constraint solver iterations; Higher values increase precision but also increase computation time
  plane_urdf_path: 'plane.urdf'
  frequency: 480              # simulation step for base and arm
  timeout : 100.0             # maximum time for planning

# Robot parameters
Robot:

  # PIDController parameters
  Controller:
    frequency : 240
    timeout : 100.0
    max_force : 500
    max_iterations : 10000
    threshold : 0.01
    max_attempts : 500
    target_distance : 0.0
    Kp : 0.01
    Ki : 0.0
    Kd : 0.0
    
  init_pose: [1, 0, 0, 0.0, 0.0, "math.pi / 2"]   # The initial pose of base and arm
  base_urdf_path: "/BestMan_Pybullet/refactor/Asset/mobile_manipulator/base/segbot/segbot.urdf"   # base urdf
  arm_urdf_path: "/BestMan_Pybullet/refactor/Asset/mobile_manipulator/arm/ur5e/ur5e_vacuum_long.urdf"   # arm urdf
  arm_joint_indexs: [0, 1, 2, 3, 4, 5]
  arm_height: 1.02   
  end_effector_index: 6
  tcp_link: 11     # The index of the end effector.
  tcp_height: 0.11  # The height of the tcp link.