Visualizer:
  Camera: 
      dist: 1.2
      position: [4.23, 5.21, 0.72]
      yaw: -89.5
      pitch: 307.4

Robot:
  init_pose: [3.5, 5.0, 0.0, 0.0, 0.0, 0.0]
  arm_urdf_path: "../Asset/mobile_manipulator/arm/panda/panda.urdf"
  arm_joints_idx: [0, 1, 2, 3, 4, 5]
  arm_init_jointValues: [0.282, -0.292, -0.583, -1.824, -0.161, 1.583]
  arm_reset_jointValues: [0.98, 0.458, 0.31, -2.24, -0.30, 2.66, 2.32]
  end_effector_index: 11