# Client parameters
Client:
  enable_GUI: True                # If True, the GUI will be enabled.
  enable_capture: True            # If True, custom image size
  width: 1280                     # W
  height: 720                     # H
  enable_Debug: False             # If False, the debug visualizer will be disabled.
  Gravity: [0, 0, -9.8]           # Simulation environment gravity coefficient
  numSolverIterations: 1000       # Set the number of constraint solver iterations; Higher values increase precision but also increase computation time
  plane_urdf_path: 'plane.urdf'   # plane
  frequency: 480                  # simulation frequency
  timeout : 100.0                 # maximum time for planning

# Visualizer params
Visualizer:
  Camera: 
      dist: 1.0
      position: [1.7, 3.68, 1.95]
      yaw: -86.4
      pitch: -52.3


# PIDController params
Controller:
  frequency : 240
  timeout : 2                # 
  max_force : 500
  max_iterations : 10000
  threshold : 0.015
  max_attempts : 500
  target_distance : 0.0
  Kp : 0.01
  Ki : 0.0
  Kd : 0.0


# Robot params
Robot:
    
  init_pose: [1, 0, 0, 0.0, 0.0, "math.pi / 2"]                                         # The initial pose of base
  init_joint: [0, -1.57, 1.5, -1.57, -1.57, 0]                                          # The initial angle of arm joint
  base_urdf_path: "../Asset/mobile_manipulator/base/segbot/segbot.urdf"                 # base urdf
  arm_urdf_path: "../Asset/mobile_manipulator/arm/ur5e/ur5e_vacuum_long.urdf"           # arm urdf
  arm_joints_idx: [0, 1, 2, 3, 4, 5]                                                    # 6 DOF
  arm_height: 1.02                                                                      # arm place height(Slightly higher than the base)
  end_effector_index: 6
  tcp_link: 11     # The index of the end effector.
  tcp_height: 0.11  # The height of the tcp link.


# Camera params
Camera:
  width: 224          # W
  height: 224         # H
  nearVal: 0.01       # Camera near viewing distance
  farVal: 20          # Camera far viewing distance


# ompl planner parameters
Planner:
  planner: "RRTConnect"
  threshold: 0.15
  max_attempts: 500
