Visualizer:
  Camera: 
      dist: 2.0
      position: [2.85, 2.4, 0.0]
      yaw: -86.4
      pitch: -40.0

Robot:
  init_pose: [2.8, 2.8, 0.0, 0.0, 0.0, 0.0]  # The initial pose of base and arm
  init_joint: [0, -1.57, 2.0, -1.57, -1.57, 0]

Planner:
  planner: "RRTConnect"       # planner