Visualizer:
  Camera: 
      dist: 2.0
      position: [2.85, 2.4, 0.0]
      yaw: -86.4
      pitch: -40.0

Robot:
  base_init_pose: [2.9, 2.5, 0.0, 0.0, 0.0, 0.0]  # The initial pose of base and arm
  arm_init_jointValues: [0, -1.57, 2.0, -1.57, -1.57, 0]

Planner:
  planner: "RRTConnect"       # planner