Visualizer:
  Camera: 
      dist: 2.0
      position: [2.0, 5.0, 1.0]
      yaw: -86.4
      pitch: -40.0

Robot:
  init_pose: [2.0, 5.0, 0, 0.0, 0.0, "math.pi / 2"]
  arm_init_jointValues: [0.98, 0.458, 0.31, -2.24, -0.30, 2.66, 2.32]                  # The initial angle of arm joint
  arm_urdf_path: "../Asset/mobile_manipulator/arm/panda/panda.urdf"          # arm urdf
  arm_joints_idx: [0, 1, 2, 3, 4, 5, 6]                                      # 7 DOF
  end_effector_index: 11
  tcp_link: -1