name: BestMan

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8.*
  - pip
  - pybind11
  - ninja
  - openblas-devel
  - yacs==0.1.8
  - networkx==3.1
  - rtree==1.2.0
  - scipy==1.10.1
  - matplotlib

  - pip:
      - numpy==1.23.5
      - PyQt5
      - opencv-python
      - pybullet==3.2.6
      - urdfpy
      - open3d
      - Install/third_party/ompl-1.6.0-cp38-cp38-manylinux_2_28_x86_64.whl
