name: BestMan

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8.*
  - pip==24.0
  - pybind11==2.12.0
  - ninja
  - openblas-devel
  - yacs==0.1.8
  - networkx==3.1
  - rtree==1.2.0
  - scipy==1.10.1

  - pip:
      - matplotlib==3.3.2
      - urdfpy==0.0.22
      - numpy==1.23.5
      - transforms3d==0.3.1
      - PyQt5==5.15.11
      - opencv-python==4.1.2.30
      - pybullet==3.2.6
      - open3d==0.18.0
      - openpyxl==3.1.5
      - Install/third_party/ompl-1.6.0-cp38-cp38-manylinux_2_28_x86_64.whl
